# Generated by Django 6.0 on 2026-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='dialog_mode',
            field=models.CharField(blank=True, default='idle', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_action',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_lang',
            field=models.CharField(blank=True, default='ru', max_length=20),
        ),
    ]
