# Generated by Django 6.0 on 2026-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_ui', '0002_chatsession_context_json_chatsession_dialog_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='bridge_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bridge_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bridge_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bridge_thread_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_bot_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_entry_point',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_step',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
