services:
  cargo_app:
    image: ghcr.io/aalam2000/cargodb:latest
    container_name: cargo_app

    command: >
      sh -c "
      python manage.py collectstatic --clear --noinput &&
      gunicorn cargodb.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 60
      "

    env_file:
      - .env.prod
      - .env.secrets

    ports:
      - "8000:8000"

    volumes:
      - /var/www/cargodb/staticfiles:/app/staticfiles
      - /var/www/cargodb/media:/app/media

    restart: unless-stopped
