# Generated by Django 5.2.7 on 2025-12-06 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Статус груза',
                'verbose_name_plural': 'Статусы грузов',
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='CarrierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Перевозчик',
                'verbose_name_plural': 'Перевозчики',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=50, verbose_name='ИНН/Tax ID')),
                ('ogrn', models.CharField(max_length=50, verbose_name='ОГРН/Registration №')),
                ('legal_address', models.CharField(max_length=500, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фактический адрес')),
                ('representative_fullname', models.CharField(max_length=255, verbose_name='Ф.И.О. представителя')),
                ('representative_basis', models.CharField(max_length=255, verbose_name='Действует на основании')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Тип упаковки',
                'verbose_name_plural': 'Типы упаковки',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_code', models.CharField(max_length=50, unique=True)),
                ('departure_place', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_place', models.CharField(blank=True, max_length=200, null=True)),
                ('weight_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('cargo_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargostatus')),
                ('last_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cargos', to='cargo_acc.cargostatus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.packagingtype')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='AccrualType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Вид начисления',
                'verbose_name_plural': 'Виды начислений',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Курс валюты к USD', max_digits=14)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Переопределённый (наш) курс', max_digits=14, null=True)),
                ('conversion_percent', models.DecimalField(decimal_places=2, default=0, help_text='Коррекция в % относительно официального курса', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'indexes': [models.Index(fields=['currency'], name='cargo_acc_c_currenc_3e70ad_idx'), models.Index(fields=['date'], name='cargo_acc_c_date_2d4fec_idx')],
                'unique_together': {('date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='ExtraCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('loading', 'Погрузка'), ('unloading', 'Разгрузка'), ('packing', 'Упаковка'), ('storage', 'Хранение'), ('customs', 'Таможня'), ('transport', 'Транспортировка'), ('other', 'Прочее')], default='other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated', models.BooleanField(default=False)),
                ('is_for_cargo', models.BooleanField(default=False, help_text='True — если расход относится ко всему грузу, False — если к товару')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargo')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extracosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дополнительная затрата',
                'verbose_name_plural': 'Дополнительные затраты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(default='img/default_image.jpg', upload_to='img/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Безнал'), ('pos', 'POS-терминал'), ('offset', 'Взаимозачёт')], default='bank', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('accrual', 'Начисление'), ('payment', 'Оплата')], default='payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cargo_acc.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cargo_acc.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('cargo_description', models.CharField(blank=True, max_length=500, null=True)),
                ('departure_place', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_place', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delivery_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('cargo_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargostatus')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargotype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('images', models.ManyToManyField(blank=True, to='cargo_acc.image')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.packagingtype')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PaymentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_product_allocations', to='cargo_acc.company')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cargo_acc.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='cargo_acc.product')),
            ],
            options={
                'verbose_name': 'Оплата по товару',
                'verbose_name_plural': 'Оплаты по товарам',
            },
        ),
        migrations.CreateModel(
            name='ExtraCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('extra_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.extracost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.product')),
            ],
            options={
                'verbose_name': 'Распределение затрат',
                'verbose_name_plural': 'Распределения затрат',
            },
        ),
        migrations.AddField(
            model_name='extracost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.product'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='products',
            field=models.ManyToManyField(blank=True, to='cargo_acc.product'),
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoded_data', models.CharField(blank=True, max_length=255, null=True)),
                ('recognized_type', models.CharField(blank=True, max_length=50, null=True)),
                ('recognized_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('recognized_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('uncertain', 'Uncertain')], default='uncertain', max_length=20)),
                ('action_result', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='cargo_acc.image')),
            ],
            options={
                'verbose_name': 'Скан QR-кода',
                'verbose_name_plural': 'Сканирование QR-кодов',
            },
        ),
        migrations.CreateModel(
            name='CargoStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cargo_acc.cargo')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargostatus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.image')),
                ('qrscan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.qrscan')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
            },
        ),
        migrations.CreateModel(
            name='TransportBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(max_length=20, unique=True)),
                ('departure_place', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_place', models.CharField(blank=True, max_length=200, null=True)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('cargos', models.ManyToManyField(to='cargo_acc.cargo')),
                ('carrier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.carriercompany')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Транспортная накладная',
                'verbose_name_plural': 'Транспортные накладные',
            },
        ),
        migrations.CreateModel(
            name='CargoMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_place', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_date', models.DateTimeField()),
                ('recognized_at', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargo')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_after_moves', to='cargo_acc.cargostatus')),
                ('status_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_before_moves', to='cargo_acc.cargostatus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.image')),
                ('qrscan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.qrscan')),
                ('from_transport_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transport_bill', to='cargo_acc.transportbill')),
                ('to_transport_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transport_bill', to='cargo_acc.transportbill')),
            ],
            options={
                'verbose_name': 'Перемещение груза',
                'verbose_name_plural': 'Перемещения грузов',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.carriercompany')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.AddField(
            model_name='transportbill',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.vehicle'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.warehouse'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'client'], name='cargo_acc_p_company_0ba729_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='cargo_acc_p_payment_86965a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproduct',
            index=models.Index(fields=['company'], name='cargo_acc_p_company_f4d870_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproduct',
            index=models.Index(fields=['product'], name='cargo_acc_p_product_963826_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentproduct',
            unique_together={('payment', 'product')},
        ),
    ]
