# Generated by Django 5.2.7 on 2025-12-06 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentproduct',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='departure_place',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='destination_place',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='last_status',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='shipping_date',
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.warehouse'),
        ),
        migrations.AddField(
            model_name='cargostatus',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_statuses', to='cargo_acc.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargotype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_types', to='cargo_acc.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carriercompany',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_companies', to='cargo_acc.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carriercompany',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='cargo_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='product_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='client_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='director_fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О. директора'),
        ),
        migrations.AddField(
            model_name='company',
            name='prefix',
            field=models.CharField(default=1, max_length=2, unique=True, verbose_name='Префикс компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to='cargo_acc.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='accrual_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrual_operations', to='cargo_acc.accrualtype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cargos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_kind',
            field=models.IntegerField(choices=[(1, 'Оплата'), (2, 'Начисление')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo_acc.cargo'),
        ),
        migrations.AlterField(
            model_name='accrualtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_types', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='accrualtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='cargomovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_movements', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cargotype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carriercompany',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='extracost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='cargo_acc.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='cargo_acc.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='transportbill',
            name='cargos',
            field=models.ManyToManyField(related_name='cargos_bills', to='cargo_acc.cargo'),
        ),
        migrations.AlterField(
            model_name='transportbill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_bills', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='cargo_acc.company'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_operations', to='cargo_acc.paymenttype'),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField()),
                ('balance_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('details_json', models.JSONField(default=dict)),
                ('hash_before', models.CharField(max_length=64)),
                ('dirty_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_snapshots', to='cargo_acc.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Срез баланса',
                'verbose_name_plural': 'Срезы баланса',
            },
        ),
        migrations.CreateModel(
            name='SystemActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
            },
        ),
        migrations.DeleteModel(
            name='CargoStatusLog',
        ),
        migrations.DeleteModel(
            name='PaymentProduct',
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['company', 'active'], name='cargo_acc_p_company_eba3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['company', 'client'], name='cargo_acc_s_company_e935a8_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['snapshot_date'], name='cargo_acc_s_snapsho_8cf632_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['dirty_flag'], name='cargo_acc_s_dirty_f_78c43b_idx'),
        ),
    ]
