# Generated by Django 5.1.4 on 2025-01-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
