# Generated by Django 5.2.7 on 2025-12-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0002_alter_paymentproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accrualtype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cargostatus',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cargotype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calc_mode', models.CharField(choices=[('weight', 'По весу'), ('volume', 'По объёму'), ('density', 'По плотности')], max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('packaging_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.cargotype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='cargo_acc.company')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
