# Generated by Django 5.2.7 on 2025-10-26 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0003_cargo_qr_code_cargo_qr_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='packaging_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='places_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tariff_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tariff_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount_original', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_source', models.CharField(default='manual', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_payload', models.TextField(blank=True, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_acc.company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='cargo_acc.cargo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_links', to='cargo_acc.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='cargo_acc_p_payment_86965a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='cargo_acc_p_client__4cf5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company'], name='cargo_acc_p_company_531683_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number', None), _negated=True), fields=('reference_number', 'payment_source'), name='uniq_payment_ref_by_source'),
        ),
        migrations.AddIndex(
            model_name='paymentcargo',
            index=models.Index(fields=['payment'], name='cargo_acc_p_payment_27ca16_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcargo',
            index=models.Index(fields=['cargo'], name='cargo_acc_p_cargo_i_087ccd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcargo',
            unique_together={('payment', 'cargo')},
        ),
    ]
