# Generated by Django 6.0 on 2025-12-18 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0003_alter_accrualtype_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='allocation_mode',
            field=models.CharField(choices=[('weight', 'По весу'), ('volume', 'По объёму'), ('items', 'Поровну по товарам'), ('value', 'По стоимости товара')], default='weight', max_length=20),
        ),
        migrations.AddField(
            model_name='cargo',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['company', 'cargo_code'], name='cargo_acc_c_company_5dfaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['company', 'cargo_status'], name='cargo_acc_c_company_230148_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['company', 'warehouse'], name='cargo_acc_c_company_ae9a08_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['company', 'created_at'], name='cargo_acc_c_company_db9e10_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['company', 'is_locked'], name='cargo_acc_c_company_fa4c88_idx'),
        ),
    ]
