# Generated by Django 6.0 on 2025-12-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0004_cargo_allocation_mode_cargo_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='cargo_acc.client'),
            preserve_default=False,
        ),
    ]
