# Generated by Django 5.2.7 on 2025-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_acc', '0004_cargo_cargo_description_cargo_packaging_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
