# Generated by Django 5.2.7 on 2025-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client_code', models.CharField(blank=True, help_text='Логин клиента. Используется для входа и фильтрации данных.', max_length=20, null=True, unique=True, verbose_name='Код Клиента')),
                ('timezone', models.CharField(default='UTC', help_text='Например: Asia/Baku, Europe/Moscow, Asia/Shanghai', max_length=50, verbose_name='Часовой пояс')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('first_name', models.CharField(blank=True, default='Не указано', max_length=30)),
                ('last_name', models.CharField(blank=True, default='Не указано', max_length=30)),
                ('phone', models.CharField(blank=True, default='Не указано', max_length=15)),
                ('telegram', models.CharField(blank=True, default='Не указано', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='Не указано', max_length=30)),
                ('website', models.URLField(blank=True, default='Не указано')),
                ('country', models.CharField(blank=True, default='Не указано', max_length=50)),
                ('city', models.CharField(blank=True, default='Не указано', max_length=50)),
                ('address', models.CharField(blank=True, default='Не указано', max_length=255)),
                ('inn', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('ogrn', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('representative', models.CharField(blank=True, default='Не указан', max_length=255)),
                ('basis', models.CharField(blank=True, default='Не указан', max_length=255)),
                ('legal_address', models.CharField(blank=True, default='Не указан', max_length=255)),
                ('actual_address', models.CharField(blank=True, default='Не указан', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='Не указан', max_length=255)),
                ('bic', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('account', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('corr_account', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('company_name', models.CharField(blank=True, default='Не указано', max_length=255)),
                ('contract_signed', models.BooleanField(default=False)),
                ('sign_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Admin', 'Администратор'), ('Operator', 'Оператор'), ('WarehouseWorker', 'Складской Работник'), ('Driver', 'Водитель'), ('Client', 'Клиент')], default='Operator', max_length=20)),
                ('access_level', models.CharField(choices=[('Company', 'Компания'), ('Branch', 'Филиал'), ('Warehouse', 'Склад')], default='Warehouse', max_length=20)),
                ('assigned_object', models.CharField(blank=True, default='', help_text='Привязка к филиалу/складу (идентификатор или код).', max_length=50)),
                ('table_settings', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
