# Generated by Django 4.2 on 2024-09-16 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
