# Generated by Django 5.2.7 on 2025-12-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cargo_acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(help_text='Компания, к которой принадлежит пользователь (обязательное поле)', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='cargo_acc.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linked_client',
            field=models.ForeignKey(blank=True, help_text='Связанный объект клиента (для роли Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cargo_acc.client'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='idx_user_email_ci'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['client_code'], name='idx_user_client_code_ci'),
        ),
    ]
