# Generated by Django 5.2.7 on 2025-12-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('cargo_acc', '0002_alter_paymentproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_cargo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_default_cargo_status', to='cargo_acc.cargostatus', verbose_name='Статус груза по умолчанию'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_cargo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_default_cargo_type', to='cargo_acc.cargotype', verbose_name='Тип груза по умолчанию'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_default_packaging_type', to='cargo_acc.packagingtype', verbose_name='Упаковка по умолчанию'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_default_warehouse', to='cargo_acc.warehouse', verbose_name='Склад по умолчанию'),
        ),
    ]
