# Generated by Django 4.2 on 2024-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="client_code",
            field=models.CharField(
                blank=True,
                default="Не указано",
                max_length=20,
                verbose_name="Код Клиента",
            ),
        ),
    ]
