# Generated by Django 4.2 on 2024-10-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_client_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="table_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
