# Generated by Django 4.2 on 2024-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_table_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Company", "Компания"),
                    ("Branch", "Филиал"),
                    ("Warehouse", "Склад"),
                ],
                default="Warehouse",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="assigned_object",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Администратор"),
                    ("Operator", "Оператор"),
                    ("WarehouseWorker", "Складской Работник"),
                    ("Driver", "Водитель"),
                ],
                default="Operator",
                max_length=20,
            ),
        ),
    ]
