# Generated by Django 5.2.7 on 2025-10-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_access_level_customuser_assigned_object_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_object',
            field=models.CharField(blank=True, default='', help_text='Привязка к филиалу/складу (идентификатор или код).', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_code',
            field=models.CharField(blank=True, help_text='Логин клиента. Используется для входа и фильтрации данных.', max_length=20, null=True, unique=True, verbose_name='Код Клиента'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('Operator', 'Оператор'), ('WarehouseWorker', 'Складской Работник'), ('Driver', 'Водитель'), ('Client', 'Клиент')], default='Operator', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='idx_user_email_ci'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['client_code'], name='idx_user_client_code_ci'),
        ),
    ]
