# Generated by Django 5.2.7 on 2025-10-27 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_and_more'),
        ('cargo_acc', '0005_alter_cargo_cargo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_client',
            field=models.ForeignKey(blank=True, help_text='Связанный объект клиента (для роли Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cargo_acc.client'),
        ),
    ]
