name: Build and Deploy

on:
  push:
    branches:
      - bonacargoprod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/aalam2000/cargodb:latest .

      - name: Push image
        run: docker push ghcr.io/aalam2000/cargodb:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 155.212.230.161
          username: cargo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker compose -f /var/www/cargodb/docker-compose.prod.yml pull
            docker compose -f /var/www/cargodb/docker-compose.prod.yml up -d